name: Vegan Chocolate Seduction Cookbook
favicon: null
layout_spectrum: 0.88628
typography_spectrum: 0.5081385225057602
title: '30 Romantic, Sexy, Playful Recipes for Passionate Chocolate Lovers'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffdd0c'
    - '#61170c'
    - '#d6b00f'
    - '#895814'
    - '#fefefe'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
