name: Vegan Chocolate Seduction Cookbook
favicon: null
layout_spectrum: 0.1481744642369449
typography_spectrum: 0.5081385225057602
title: '30 Romantic, Sexy, Playful Recipes for Passionate Chocolate Lovers'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1544324008282274
  lightness: 0.8390691413078457
  saturation: 0.28787629143334925
  rhythmicContrast: 0.5247583300806582
purpose: []
